language: java
jdk:
  - openjdk8
branches:
  only:
    - master
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
#  - zip -r sampleProject *
#  - mkdir -p deploy
#  - mv sampleProject.zip deploy/sampleProject.zip
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/sampleProject.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #travis repo setting
    secret_access_key: $AWS_SECRET_KEY
    bucket: chanchul-test-build #S3 bucket
    skip_clean: true
    acl: private #zip파일 접근 private
    local_dir: deploy
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: chanchul-test-build #S3 bucket
    key: sampleProject.zip
    bundle_type: zip
    application: chanchul-test-web-service
    deployment_group: chanchul-test-web-service-group
    region: ap-northeast-2
    wait-until-deploy: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - jjchc@naver.com

before_install:
  - chmod +x gradlew

